version: 5
daemon:
  log_level: info
  admin_group: wheel
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  1002:6FDF-1002:0B31-0000:03:00.0:
    fan_control_enabled: true
    fan_control_settings:
      mode: curve
      static_speed: 0.89132077
      temperature_key: edge
      interval_ms: 500
      curve:
        30: 0.2
        40: 0.35
        50: 0.5
        60: 0.75
        70: 1.0
      spindown_delay_ms: 5000
      change_threshold: 2
    performance_level: auto
    max_core_clock: 1200
  1002:6FDF-1002:0B31-0000:01:00.0:
    fan_control_enabled: true
    fan_control_settings:
      mode: curve
      static_speed: 0.5
      temperature_key: edge
      interval_ms: 500
      curve:
        30: 0.30338982
        40: 0.40169492
        50: 0.5983051
        70: 0.9983051
        90: 1.0
      spindown_delay_ms: 5000
      change_threshold: 2
    performance_level: auto
    max_core_clock: 1350
    max_voltage: 1060
profiles:
  test:
    gpus:
      1002:6FDF-1002:0B31-0000:03:00.0:
        fan_control_enabled: true
        fan_control_settings:
          mode: curve
          static_speed: 0.89132077
          temperature_key: edge
          interval_ms: 500
          curve:
            30: 0.2
            40: 0.35
            50: 0.5
            60: 0.75
            70: 1.0
          spindown_delay_ms: 5000
          change_threshold: 2
        performance_level: auto
        max_core_clock: 1200
      1002:6FDF-1002:0B31-0000:01:00.0:
        fan_control_enabled: true
        fan_control_settings:
          mode: curve
          static_speed: 0.5
          temperature_key: edge
          interval_ms: 500
          curve:
            30: 0.30338982
            40: 0.40169492
            50: 0.5983051
            70: 0.9983051
            90: 1.0
          spindown_delay_ms: 5000
          change_threshold: 2
        performance_level: auto
        max_core_clock: 1350
        max_voltage: 1060
    rule:
      type: gamemode
      filter: null
current_profile: null
auto_switch_profiles: true
